### ISSUE TITLE
Failed installing with pip

### ISSUE THREAD

**Issue by luizhdinizf** [kkdai/docker-python3-opencv-face_recognition#1]
i have downloaded your image from docker hub
https://hub.docker.com/r/kkdai/docker-python3-opencv-face_recognition
how can i install libraries via pip after pulled the image?
ex:
pip install flask
pip install pymongo
it returns an erro if i run:
docker run -ti kkdai/docker-python3-opencv-face_recognition  "pip install flask pymongo" 
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"pip install flask pymongo\": executable file not found in $PATH": unknown.

or just launch with a tty console instead of python console?

**Comment by kkdai** [comment]
Hi 
Sorry for the late reply.
You should try this https://stackoverflow.com/questions/40534274/add-pip-requirements-to-docker-image-in-runtime

**Comment by kkdai** [comment]
Let me know if you have any question.
